//HintName: TestClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public class TestClassReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::TestNamespace.TestClass _reflectedObject;

    public TestClassReflector(global::TestNamespace.TestClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Name", typeof(string), true),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Address", typeof(global::TestNamespace.Address), true),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Tags", typeof(global::System.Collections.Generic.List<string>), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "name":
                    return _reflectedObject.Name;
                case "address":
                    return _reflectedObject.Address;
                case "tags":
                    return _reflectedObject.Tags;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in TestClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "name":
                    if (value is not null and not string)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a string value.");

                    _reflectedObject.Name = (string)value;
                    break;

                case "address":
                    if (value is not null and not global::TestNamespace.Address)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a global::TestNamespace.Address value.");

                    _reflectedObject.Address = (global::TestNamespace.Address)value;
                    break;

                case "tags":
                    if (value is not null and not global::System.Collections.Generic.List<string>)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a global::System.Collections.Generic.List<string> value.");

                    _reflectedObject.Tags = (global::System.Collections.Generic.List<string>)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }
}
}
