//HintName: MyApp_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace MyApp
{
internal static class ReflectorExtensions
{
    internal static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        return null;
    }
}
}
