//HintName: GlobalReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::TestNamespace.EmptyClass emptyClass)
            return new EmptyClassReflector(emptyClass);

        return null;
    }
}
