//HintName: SecondClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace SecondNamespace
{
public class SecondClassReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::SecondNamespace.SecondClass _reflectedObject;

    public SecondClassReflector(global::SecondNamespace.SecondClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Value", typeof(int), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "value":
                    return _reflectedObject.Value;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in SecondClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "value":
                    if (value is not null and not int)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in SecondClassReflector. Expected a int value.");

                    _reflectedObject.Value = (int)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in SecondClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }
}
}
