//HintName: TestClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
internal partial class TestClass : global::Shiny.Reflector.IHasReflectorClass
{
     private global::Shiny.Reflector.IReflectorClass? _reflector;
    internal global::Shiny.Reflector.IReflectorClass Reflector => _reflector ??= new TestClassReflector(this);
}
}
