//HintName: Common_Extensions_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace Common.Extensions
{
public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::FirstNamespace.FirstClass firstClass)
            return new FirstClassReflector(firstClass);

        if (obj is global::SecondNamespace.SecondClass secondClass)
            return new SecondClassReflector(secondClass);

        return null;
    }
}
}
