//HintName: TestClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public class TestClassReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::TestNamespace.TestClass _reflectedObject;

    public TestClassReflector(global::TestNamespace.TestClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Name", typeof(string), false),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Age", typeof(int), false),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Value", typeof(double), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "name":
                    return _reflectedObject.Name;
                case "age":
                    return _reflectedObject.Age;
                case "value":
                    return _reflectedObject.Value;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in TestClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "value":
                    if (value is not null and not double)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a double value.");

                    _reflectedObject.Value = (double)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }
}
}
