//HintName: TestRecord_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public partial record TestRecord : global::Shiny.Reflector.IHasReflectorClass
{
     private global::Shiny.Reflector.IReflectorClass? _reflector;
    public global::Shiny.Reflector.IReflectorClass Reflector => _reflector ??= new TestRecordReflector(this);
}
}
