//HintName: EmptyClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public partial class EmptyClass
{
    public global::Shiny.Reflector.IReflectorClass Reflector { get; } = new EmptyClassReflector(this);
}
}
