//HintName: TestRecordReflector.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public class TestRecordReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::TestNamespace.TestRecord _reflectedObject;

    public TestRecordReflector(global::TestNamespace.TestRecord reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Name", typeof(string), false),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Age", typeof(int), false),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Value", typeof(double), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "name":
                    return _reflectedObject.Name;
                case "age":
                    return _reflectedObject.Age;
                case "value":
                    return _reflectedObject.Value;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in TestRecordReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "value":
                    if (value is not null and not double)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestRecordReflector. Expected a double value.");

                    _reflectedObject.Value = (double)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestRecordReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }

    public global::Shiny.Reflector.AttributeInfo[] Attributes => new global::Shiny.Reflector.AttributeInfo[]
    {
        new global::Shiny.Reflector.AttributeInfo(
            typeof(System.ObsoleteAttribute),
            new global::Shiny.Reflector.AttributeArgumentInfo[]
            {
            }
        ),
        new global::Shiny.Reflector.AttributeInfo(
            typeof(System.ComponentModel.DescriptionAttribute),
            new global::Shiny.Reflector.AttributeArgumentInfo[]
            {
                new global::Shiny.Reflector.AttributeArgumentInfo(
                    typeof(string),
                    "description",
                    "Test record",
                    false,
                    null
                )
            }
        ),
        new global::Shiny.Reflector.AttributeInfo(
            typeof(Shiny.Reflector.ReflectorAttribute),
            new global::Shiny.Reflector.AttributeArgumentInfo[]
            {
            }
        )
    };
}
}
