//HintName: SecondNamespace_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace SecondNamespace
{
public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::SecondNamespace.SecondClass secondClass)
            return new SecondClassReflector(secondClass);

        return null;
    }
}
}
