//HintName: FirstClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace FirstNamespace
{
public class FirstClassReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::FirstNamespace.FirstClass _reflectedObject;

    public FirstClassReflector(global::FirstNamespace.FirstClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Name", typeof(string), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "name":
                    return _reflectedObject.Name;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in FirstClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "name":
                    if (value is not null and not string)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in FirstClassReflector. Expected a string value.");

                    _reflectedObject.Name = (string)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in FirstClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }
}
}
