//HintName: EmptyClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public partial class EmptyClass : global::Shiny.Reflector.IHasReflectorClass
{
     private global::Shiny.Reflector.IReflectorClass? _reflector;
    public global::Shiny.Reflector.IReflectorClass Reflector => _reflector ??= new EmptyClassReflector(this);
}
}
