//HintName: MyApp_Extensions_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace MyApp.Extensions
{
internal static class ReflectorExtensions
{
    internal static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::TestNamespace.TestClass testClass)
            return new TestClassReflector(testClass);

        return null;
    }
}
}
