//HintName: MyApp_Extensions_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace MyApp.Extensions
{
public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        return null;
    }
}
}
