//HintName: TestNamespace_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::TestNamespace.FirstClass firstClass)
            return new FirstClassReflector(firstClass);

        if (obj is global::TestNamespace.SecondClass secondClass)
            return new SecondClassReflector(secondClass);

        return null;
    }
}
}
