//HintName: FirstNamespace_ReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

namespace FirstNamespace
{
public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        if (obj is global::FirstNamespace.FirstClass firstClass)
            return new FirstClassReflector(firstClass);

        return null;
    }
}
}
