//HintName: TestClassReflector.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public class TestClassReflector : global::Shiny.Reflector.IReflectorClass
{
    private readonly global::TestNamespace.TestClass _reflectedObject;

    public TestClassReflector(global::TestNamespace.TestClass reflectedObject)
    {
        _reflectedObject = reflectedObject;
    }

    public object ReflectedObject => _reflectedObject;

    public global::Shiny.Reflector.PropertyGeneratedInfo[] Properties => new global::Shiny.Reflector.PropertyGeneratedInfo[]
    {
        new global::Shiny.Reflector.PropertyGeneratedInfo("Names", typeof(global::System.Collections.Generic.List<string>), true),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Values", typeof(global::System.Collections.Generic.Dictionary<string, int>), true),
        new global::Shiny.Reflector.PropertyGeneratedInfo("Dates", typeof(global::System.Collections.Generic.IEnumerable<global::System.DateTime>), true)
    };

    public T? GetValue<T>(string key)
    {
        var value = this[key];
        if (value == null)
            return default(T);

        return (T)value;
    }

    public object? this[string key]
    {
        get
        {
            switch (key?.ToLower())
            {
                case "names":
                    return _reflectedObject.Names;
                case "values":
                    return _reflectedObject.Values;
                case "dates":
                    return _reflectedObject.Dates;
                default:
                    throw new global::System.InvalidOperationException($"Cannot get value for key '{key}' in TestClassReflector");
            }
        }
        set
        {
            switch (key?.ToLower())
            {
                case "names":
                    if (value is not null and not global::System.Collections.Generic.List<string>)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a global::System.Collections.Generic.List<string> value.");

                    _reflectedObject.Names = (global::System.Collections.Generic.List<string>)value;
                    break;

                case "values":
                    if (value is not null and not global::System.Collections.Generic.Dictionary<string, int>)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a global::System.Collections.Generic.Dictionary<string, int> value.");

                    _reflectedObject.Values = (global::System.Collections.Generic.Dictionary<string, int>)value;
                    break;

                case "dates":
                    if (value is not null and not global::System.Collections.Generic.IEnumerable<global::System.DateTime>)
                        throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector. Expected a global::System.Collections.Generic.IEnumerable<global::System.DateTime> value.");

                    _reflectedObject.Dates = (global::System.Collections.Generic.IEnumerable<global::System.DateTime>)value;
                    break;

                default:
                    throw new global::System.InvalidOperationException($"Cannot set value for key '{key}' in TestClassReflector");
            }
        }
    }

    public void SetValue<T>(string key, T? value)
    {
        this[key] = value;
    }

    public global::Shiny.Reflector.AttributeInfo[] Attributes => new global::Shiny.Reflector.AttributeInfo[]
    {
        new global::Shiny.Reflector.AttributeInfo(
            typeof(Shiny.Reflector.ReflectorAttribute),
            new global::Shiny.Reflector.AttributeArgumentInfo[]
            {
            }
        )
    };
}
}
