//HintName: TestClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
public partial class TestClass
{
    public global::Shiny.Reflector.IReflectorClass Reflector { get; } = new TestClassReflector(this);
}
}
