//HintName: TestClass_ReflectorProperty.g.cs
// <auto-generated />
#nullable enable

namespace TestNamespace
{
internal partial class TestClass
{
    internal global::Shiny.Reflector.IReflectorClass Reflector { get; } = new TestClassReflector(this);
}
}
