//HintName: GlobalReflectorExtensions.g.cs
// <auto-generated />
#nullable enable

public static class ReflectorExtensions
{
    public static global::Shiny.Reflector.IReflectorClass? GetReflector(this object obj)
    {
        return null;
    }
}
